spring:
  jpa:
    hibernate:
      ddl-auto:
          none
    generate-ddl:
        false
server:
  port:
    8080

management:
  endpoints:
    web:
      exposure:
        include:
          - env
          - health
          - info
          - prometheus
  endpoint:
    health:
      show-details:
        always
  metrics:
    export:
      prometheus:
        enabled:
          true